name: Upload and Pin to Crust

on:
  push:
    branches:
    - gh-pages

jobs:
  upload-to-ipfs:
    name: aip-page-uploader
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Remove gitfiles
      run: rm -rf .git

    - name: Upload to Crust and IPFS
      id: upload
      uses: crustio/ipfs-upload-action@1.0.2
      with:
        path: './'
        seeds: ${{ secrets.CRUST_SECRET_KEY }}

    - name: Pin to Crust
        uses: crustio/ipfs-crust-action@v1.0.8
        continue-on-error: true
        timeout-minutes: 2
        with:
          cid: ${{ steps.upload.outputs.hash }}
          seeds: ${{ secrets.CRUST_SEEDS }}
